name: inception
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - atomicwrites=1.3.0
  - attrs=19.1.0
  - bzip2=1.0.8
  - ca-certificates=2019.9.11
  - certifi=2019.9.11
  - cffi=1.12.3
  - entrypoints=0.3
  - flake8=3.7.8
  - importlib_metadata=0.23
  - intel-openmp=2019.4
  - joblib=0.13.2
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcxx=9.0.0
  - libcxxabi=9.0.0
  - libffi=3.2.1
  - libgfortran=4.0.0
  - liblapack=3.8.0
  - libopenblas=0.3.7
  - llvm-openmp=8.0.1
  - mccabe=0.6.1
  - mkl=2019.4
  - more-itertools=7.2.0
  - mypy=0.730
  - mypy_extensions=0.4.1
  - ncurses=6.1
  - ninja=1.9.0
  - numpy=1.17.2
  - openssl=1.1.1c
  - packaging=19.2
  - pip=19.2.3
  - pluggy=0.13.0
  - psutil=5.6.3
  - py=1.8.0
  - pycodestyle=2.5.0
  - pycparser=2.19
  - pyflakes=2.1.1
  - pyparsing=2.4.2
  - pytest=5.0.1
  - pytest-flake8=1.0.4
  - python=3.7.3
  - pytorch=1.2.0
  - readline=8.0
  - scikit-learn=0.21.3
  - scipy=1.3.1
  - setuptools=41.2.0
  - six=1.12.0
  - sqlite=3.29.0
  - tk=8.6.9
  - typed-ast=1.4.0
  - typing_extensions=3.7.4
  - wcwidth=0.1.7
  - wheel=0.33.6
  - xz=5.2.4
  - zipp=0.6.0
  - zlib=1.2.11
